// Generated by @seyuna/generator — do not edit by hand. Source: scaffold/astro.config.ts
import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import cloudflare from '@astrojs/cloudflare';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  output: 'server',
  adapter: cloudflare({ platformProxy: { enabled: true } }),
  integrations: [react()],
  vite: { plugins: [tailwindcss()] },
  // Astro's checkOrigin rejects cross-origin POSTs with a 403. That breaks webhooks
  // (Stripe/GitHub/etc. obviously won't send a matching Origin header). We rely on
  // per-route auth instead: signature verification for webhooks, Better Auth sessions
  // for /api/actions/*, and presign-time auth for uploads (Phase 4).
  security: { checkOrigin: false },
});
