// Generated by @seyuna/generator — do not edit by hand. Source: scaffold/drizzle.config.ts
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './drizzle/schema.ts',
  out: './drizzle',
  dialect: 'turso',
  dbCredentials: {
    url: process.env.TURSO_URL ?? '',
    authToken: process.env.TURSO_AUTH_TOKEN ?? '',
  },
});
