-- Generated by @seyuna/generator — drizzle emitter.
CREATE TABLE `todo` (
  id TEXT PRIMARY KEY NOT NULL,
  completed INTEGER NOT NULL,
  title TEXT NOT NULL,
  user_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  user_id TEXT NOT NULL
);

CREATE INDEX `todo_user_id_idx` ON `todo` (`user_id`);
