// Generated by @seyuna/generator — drizzle emitter.
import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core';

export const todo = sqliteTable('todo', {
  id: text('id').primaryKey(),
  completed: integer('completed').notNull(),
  title: text('title').notNull(),
  userId: text('user_id').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  userId: text('user_id').notNull(),
},
(t) => ({
  userIdIdx: index('todo_user_id_idx').on(t.userId),
}));
