// Generated by @seyuna/generator — hono emitter.
import { z } from 'zod';
import { serverAction, type ActionContext } from '@seyuna/runtime-sdk/server';

const inputSchema = z.object({
  id: z.string(),
});
export type CompleteTodoInput = z.infer<typeof inputSchema>;

export const route = serverAction(
  {
    name: 'completeTodo',
    parseInput: (raw: unknown) => inputSchema.parse(raw),
  },
  async (input, _ctx: ActionContext) => {
    return { model: 'Todo', updated: input };
  },
);
