// Generated by @seyuna/generator — hono emitter.
import { z } from 'zod';
import { serverAction, type ActionContext } from '@seyuna/runtime-sdk/server';

const inputSchema = z.object({
  title: z.string(),
});
export type CreateTodoInput = z.infer<typeof inputSchema>;

export const route = serverAction(
  {
    name: 'createTodo',
    parseInput: (raw: unknown) => inputSchema.parse(raw),
  },
  async (input, _ctx: ActionContext) => {
    // Phase 1 stub: persistence not yet wired in apps without a DB binding.
    return { id: 'todo-createTodo', model: 'Todo', input };
  },
);
