// Generated by @seyuna/generator — hono emitter.
import { Hono } from 'hono';
import type { Session } from '@seyuna/runtime-sdk';
import { route as actions_completeTodo } from '../api/actions/completeTodo.js';
import { route as actions_createTodo } from '../api/actions/createTodo.js';
import { route as actions_deleteTodo } from '../api/actions/deleteTodo.js';
import { route as actions_listTodos } from '../api/actions/listTodos.js';
import { list as models_todo_list } from '../api/models/todo.js';



type AppEnv = { Bindings: Env; Variables: { session: Session | null } };

// Mounted at /api/* by src/pages/api/[...path].ts (Astro catch-all bridge).
const app = new Hono<AppEnv>().basePath('/api');

app.get('/healthz', (c) => c.json({ ok: true }));

app.post('/actions/completeTodo', (c) => actions_completeTodo.fetch(c.req.raw, c.env as Record<string, unknown>, c.var.session ?? null));
app.post('/actions/createTodo', (c) => actions_createTodo.fetch(c.req.raw, c.env as Record<string, unknown>, c.var.session ?? null));
app.post('/actions/deleteTodo', (c) => actions_deleteTodo.fetch(c.req.raw, c.env as Record<string, unknown>, c.var.session ?? null));
app.post('/actions/listTodos', (c) => actions_listTodos.fetch(c.req.raw, c.env as Record<string, unknown>, c.var.session ?? null));

app.get('/models/todo/list', models_todo_list);





export default app;
