// Generated by @seyuna/generator — hono emitter.
import type { APIRoute } from 'astro';
import app from '../../api/index.js';

export const prerender = false;

const handler: APIRoute = ({ request, locals }) => {
  // @astrojs/cloudflare exposes the Workers env on locals via the Runtime type
  // declared in src/env.d.ts. App.Locals extends Runtime<Env>, so locals.env is
  // the bindings object and locals.ctx is the ExecutionContext.
  return app.fetch(request, locals.env, locals.ctx);
};

export const GET = handler;
export const POST = handler;
export const PUT = handler;
export const DELETE = handler;
export const PATCH = handler;
export const OPTIONS = handler;
export const HEAD = handler;
