// Vendored from @seyuna/runtime-sdk. Do not edit — regenerate to update.
'use client';

import { useCallback, useState } from 'react';

interface UseActionState<O> {
  data: O | null;
  loading: boolean;
  error: Error | null;
}

interface UseActionReturn<I, O> extends UseActionState<O> {
  run: (input: I) => Promise<O>;
  reset: () => void;
}

/**
 * Call a named server action. The hook POSTs the input to `/api/actions/<name>` and
 * resolves with the action's typed output. State (loading, error, last result) lives
 * in `useState` so the component can render in-flight UI without a separate store.
 *
 * Generated by the page emitter when a block references an action via `props.action`
 * or `bind.action`. End-users compose this hook directly in any client island.
 */
export function useAction<I, O>(name: string): UseActionReturn<I, O> {
  const [state, setState] = useState<UseActionState<O>>({
    data: null,
    loading: false,
    error: null,
  });

  const run = useCallback(
    async (input: I): Promise<O> => {
      setState({ data: null, loading: true, error: null });
      try {
        const res = await fetch(`/api/actions/${name}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          credentials: 'include',
          body: JSON.stringify(input),
        });
        const json = (await res.json()) as
          | { ok: true; data: O }
          | { ok: false; error: { code: string; message: string } };
        if (!res.ok || !json.ok) {
          const message = json.ok ? `HTTP ${res.status}` : json.error.message;
          const err = new Error(message);
          setState({ data: null, loading: false, error: err });
          throw err;
        }
        setState({ data: json.data, loading: false, error: null });
        return json.data;
      } catch (err) {
        const e = err instanceof Error ? err : new Error(String(err));
        setState({ data: null, loading: false, error: e });
        throw e;
      }
    },
    [name],
  );

  const reset = useCallback(() => {
    setState({ data: null, loading: false, error: null });
  }, []);

  return { ...state, run, reset };
}
