// Generated by @seyuna/generator — auth emitter.
import { betterAuth } from 'better-auth';

interface AuthEnv {
  BETTER_AUTH_SECRET?: string;
  BETTER_AUTH_URL?: string;
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  APPLE_CLIENT_ID?: string;
  APPLE_CLIENT_SECRET?: string;
  MICROSOFT_CLIENT_ID?: string;
  MICROSOFT_CLIENT_SECRET?: string;
  SLACK_CLIENT_ID?: string;
  SLACK_CLIENT_SECRET?: string;
}

export function createAuth(env: AuthEnv) {
  return betterAuth({
    secret: env.BETTER_AUTH_SECRET ?? 'dev-secret-change-me',
    baseURL: env.BETTER_AUTH_URL ?? 'http://localhost:8787',
    emailAndPassword: { enabled: true, requireEmailVerification: false },
    plugins: [],
    socialProviders: {

    },
  });
}
