// Generated by @seyuna/generator — hono emitter.
import type { Context } from 'hono';
import { applyRls } from '@seyuna/runtime-sdk/server';

export async function list(c: Context) {
  // Phase-1 stub: returns an empty list with RLS guards in place.
  const session = c.var.session ?? null;
  const rows: Array<Record<string, unknown>> = [];
  return c.json({ ok: true, data: applyRls(rows, session, { ownerField: 'userId' }) });
}
